### PR TITLE
X bomb

### PR DESCRIPTION
**Pull request by hackerxphantom**

### CODE REVIEW

**Comment by shivaraj8050228524** [comment]
What's app hack how

**Comment by hackerxphantom** [comment]
There are methods to hack

**Comment by Smkswa** [comment]
bro please help me my Facebook account was hacked

**Comment by 766770** [comment]
My Facebook account is hack

**Review by Subhajit099 — COMMENTED** [review]
918675https://www.facebook.com/tapas.guria.12?mibextid=ZbWKwL

**Review by Freakyty — COMMENTED** [review]
I hope I don't disappoint you

**Comment by haqn99786-sketch** [comment]
+923346012670 this number is crash please 🙏

**Pull request merged**
